version: "3.8"

services:
  db:
    image: postgres:14
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lab3_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: flask_api
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: "app.py"
      FLASK_RUN_HOST: "0.0.0.0"
      DATABASE_URL: "postgresql://postgres:1234@db:5432/lab3_db"
      JWT_SECRET_KEY: "49f3e93ac0406b75986c9ca36e941614ca2471c190b9b4d85e89af996b0da0b9"
    ports:
      - "5001:5000"
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"


volumes:
  postgres_data:
